# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' A simple script to get the central difference gradient of a (image) matrix
#'
#' @param x a matrix representing the image
#' @return the first derivative (central difference gradient) of that matrix
#'
#' @export
grad1_c <- function(x) {
    .Call('_shapAAR_grad1_c', PACKAGE = 'shapAAR', x)
}

